<!DOCTYPE html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>AIMIT HUB 2016</title>
      
</head>
<body>
  <?php include('header.php');?>
        <div id="page-wrapper">
            <div id="page-inner">
                <div class="row">
                    <div class="col-md-12">
                        <h1 >Leave Application Submission and Status</h1>
                        <h1 class="page-subhead-line">Welcome to AIMIT HUB </h1>

                    </div>
                </div>
				
				<div class="row">
                <div class="col-md-12">
                  <!--   Assignments -->
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3><b>Leave Applications</b></h3>
                        </div>
                        <div class="panel-body">
                            <div >
                                From  <input type="text" />
								<br>
								<br>
								To   <input type="text" /><br><br>
								<br>
								Subject <input type="text"   style="margin: 0px; width: 500px; height: 20px;" /><br><br>
								Reason for the Absence<br>
								<textarea height="400" width="400" style="margin: 0px; width: 551px; height: 261px;"></textarea><br><br>
								<br>
								<br>
								<div class="panel panel-default">
								<div class="panel-heading">
								<h4>Subjects</h3>
								<b>9:00 AM to 10:00 AM</b><br>

								<select>
								
								<option>P.601.3(E1) Data structure & Analysis of Algorithms</option>
								<option>P.602.3(E1) Software Engineering</option>
								<option>P.603.3(E1)Object Oriented programming with Java</option>
								<option>P.604.3(E1)Database Management System</option>
								<option>P.605.3(E2)Optimization Technique</option>
								<option>P.606.3 Data Structures using Java UML Lab</option>
								<option>P.607.3 Java programming & DBMS Lab</option>
								<option>P.608.3 Business Communication</option>
								
								</select>
								<br>
								<b>10:00 AM to 11:00 AM</b><br>
								
								
								<select>
								
								<option>P.601.3(E1) Data structure & Analysis of Algorithms</option>
								<option>P.602.3(E1) Software Engineering</option>
								<option>P.603.3(E1)Object Oriented programming with Java</option>
								<option>P.604.3(E1)Database Management System</option>
								<option>P.605.3(E2)Optimization Technique</option>
								<option>P.606.3 Data Structures using Java UML Lab</option>
								<option>P.607.3 Java programming & DBMS Lab</option>
								<option>P.608.3 Business Communication</option>
								
								</select>
								<br>
								<b>11:00 AM to 12:00 PM</b><br>
								
								<select>
								
								<option>P.601.3(E1) Data structure & Analysis of Algorithms</option>
								<option>P.602.3(E1) Software Engineering</option>
								<option>P.603.3(E1)Object Oriented programming with Java</option>
								<option>P.604.3(E1)Database Management System</option>
								<option>P.605.3(E2)Optimization Technique</option>
								<option>P.606.3 Data Structures using Java UML Lab</option>
								<option>P.607.3 Java programming & DBMS Lab</option>
								<option>P.608.3 Business Communication</option>
								
								</select>
								<br>
								<b>12:00 PM to 1:00 PM</b><br>
								
								<select>
								
								<option>P.601.3(E1) Data structure & Analysis of Algorithms</option>
								<option>P.602.3(E1) Software Engineering</option>
								<option>P.603.3(E1)Object Oriented programming with Java</option>
								<option>P.604.3(E1)Database Management System</option>
								<option>P.605.3(E2)Optimization Technique</option>
								<option>P.606.3 Data Structures using Java UML Lab</option>
								<option>P.607.3 Java programming & DBMS Lab</option>
								<option>P.608.3 Business Communication</option>
								
								</select>
								<br>
								<b>2:00 PM to 3:00 PM</b><br>
								<select>
								
								<option>P.601.3(E1) Data structure & Analysis of Algorithms</option>
								<option>P.602.3(E1) Software Engineering</option>
								<option>P.603.3(E1)Object Oriented programming with Java</option>
								<option>P.604.3(E1)Database Management System</option>
								<option>P.605.3(E2)Optimization Technique</option>
								<option>P.606.3 Data Structures using Java UML Lab</option>
								<option>P.607.3 Java programming & DBMS Lab</option>
								<option>P.608.3 Business Communication</option>
								
								</select>
								<br>
								<b>3:00 PM tO 4:00 PM</b><br>
								<select>
								
								<option>P.601.3(E1) Data structure & Analysis of Algorithms</option>
								<option>P.602.3(E1) Software Engineering</option>
								<option>P.603.3(E1)Object Oriented programming with Java</option>
								<option>P.604.3(E1)Database Management System</option>
								<option>P.605.3(E2)Optimization Technique</option>
								<option>P.606.3 Data Structures using Java UML Lab</option>
								<option>P.607.3 Java programming & DBMS Lab</option>
								<option>P.608.3 Business Communication</option>
								
								</select>
								<br>
								<b>4:00PM to 5:00 PM</b><br>
								<select>
								
								<option>P.601.3(E1) Data structure & Analysis of Algorithms</option>
								<option>P.602.3(E1) Software Engineering</option>
								<option>P.603.3(E1)Object Oriented programming with Java</option>
								<option>P.604.3(E1)Database Management System</option>
								<option>P.605.3(E2)Optimization Technique</option>
								<option>P.606.3 Data Structures using Java UML Lab</option>
								<option>P.607.3 Java programming & DBMS Lab</option>
								<option>P.608.3 Business Communication</option>
								
								</select>
								<br>
								<br>
								<input type="button" value="Submit"></input>
								
								</div>
								</div>
								
								
								
								
								
								
								
								
                            </div>
                        </div>
                    </div>
                     <!-- End  completed -->
                </div>
				</div>
				</div>
				
				
				 <!-- /. PAGE INNER  -->
        </div>
        <!-- /. PAGE WRAPPER  -->
    </div>
    <!-- /. WRAPPER  -->
    <div id="footer-sec">
        &copy; AIMIT HUB | Design By :Arun Jose,Puneeth Pai & Kevin Milan Sequeira <br><a href="http://www.aimithub2016.com/" target="_blank">www.aimithub2016.com</a></br>
    </div>
    <!-- /. FOOTER  -->
    <!-- SCRIPTS -AT THE BOTOM TO REDUCE THE LOAD TIME-->
    <!-- JQUERY SCRIPTS -->
    <script src="assets/js/jquery-1.10.2.js"></script>
    <!-- BOOTSTRAP SCRIPTS -->
    <script src="assets/js/bootstrap.js"></script>
    <!-- METISMENU SCRIPTS -->
    <script src="assets/js/jquery.metisMenu.js"></script>
    <!-- CUSTOM SCRIPTS -->
    <script src="assets/js/custom.js"></script>


</body>
</html>
